package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager() {
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId() {
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void testAddTaskWithAndWithoutId() {
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "task predefined id should not change");
    }

    @Test
    public void checkTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(task1after.getId(), id);
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    public void checkTaskUpdate() {
        Task task = new Task(1, "Task 1", "Test task", TaskStatus.NEW);
        Task updateTask = new Task(1, "Task 1 new", "Test task new", TaskStatus.DONE);
        manager.addNewTask(task);
        manager.updateTask(updateTask);
        assertEquals(1, manager.getTasks().size());
        assertEquals(updateTask, manager.getTask(1));
    }

    @Test
    public void checkSubTaskStatusUpdate() {
        Epic epic = new Epic(1, "Epic", "epic");
        Subtask subtask = new Subtask(2, "Subtask", "subtask", TaskStatus.NEW, 1);
        Subtask newSubtask = new Subtask(2, "Subtask", "subtask", TaskStatus.DONE, 1);
        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask);
        assertEquals(TaskStatus.NEW, manager.getEpic(1).getStatus());
        manager.updateSubtask(newSubtask);
        assertEquals(TaskStatus.DONE, manager.getEpic(1).getStatus());
    }

    @Test
    public void checkDeleteEpic() {
        Epic epic = new Epic(1, "Epic", "epic");
        Subtask subtask = new Subtask(2, "Subtask", "subtask", TaskStatus.NEW, 1);
        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask);
        manager.deleteEpic(1);
        assertEquals(0, manager.getSubtasks().size());
    }
}
